## attemptFrequency controls how often DesirePaths will roll the dice to change blocks.
## attemptFrequency is in ticks. 20 ticks = 1 second. IT IS HIGHLY DISCOURAGED TO SET THIS BELOW 5!!!
## Increase this number if you run into any performance issues but the effect of DesirePaths will be less apparent.
## THIS VALUE DOES NOT CHANGE WITH </desirepaths reload> YOU MUST RESTART THE SERVER FOR THIS TO TAKE EFFECT!
attemptFrequency: 10

## List of worlds that DesirePaths will not affect.
disabledWorlds:
  - exampleworld

## movementCheckEnabled determines if we should run an extra check to see if the player is currently moving.
## Setting this to true means that unless a player is actively moving around we won't change the block below them.
## This setting will have an impact on the plugin's performance, if you have issues you should set this to false.
movementCheckEnabled: false

## speedBoostOnPaths is an extra addon that just makes it so that players receive a slight speed boost when walking path blocks
## enabling this option might encourage your players to use the same paths more regularly.
speedBoost:
  enabled: false
  ##boostedWalkSpeed is what the player's movement speed should be set as when they walk on the blocks you've specified.
  ##minecraft's default walk speed is 0.2 after the player is no longer on your specified path blocks their speed will be reset to that.
  ## value must be between 0 - 1
  boostedWalkSpeed: 0.25
  boostOnBlocks:
    - DIRT_PATH

## chanceModifiers for block changes.
## Chances are out of 100.
chanceModifiers:
  RIDING_HORSE: 37
  RIDING_BOAT: 99
  RIDING_PIG: 30
  FEATHER_FALLING: 10
  HAS_BOOTS: 20
  LEATHER_BOOTS: 11
  NO_BOOTS: 3
## SPRINTING_BLOCK_BELOW and SPRINTING_BLOCK_AT_FEET are added to the chance from the other modifiers.
## They are only added when the player is sprinting.
  SPRINTING_BLOCK_BELOW: 13
  SPRINTING_BLOCK_AT_FEET: 100

## blockModifications are how DesirePaths knows which blocks to check for as well as what blocks they should turn into
## ex. Dirt turns into Diamond Blocks -> DIRT:DIAMOND_BLOCK
## Use blocks from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
## Avoid adding tons of blocks to this list as it could possibly affect performance
blockModifications:
## Blocks at the same level as the player's feet
  blockAtFeetModifications:
    - SNOW:AIR
    - GRASS:AIR
    - FERN:AIR
    - TALL_GRASS:GRASS
## Blocks below that the player is standing on
  blockBelowModifications:
    - GRASS_BLOCK:DIRT
    - DIRT:COARSE_DIRT
    - PODZOL:COARSE_DIRT
    - COARSE_DIRT:DIRT_PATH
    - SANDSTONE:SAND
    - CRIMSON_NYLIUM:NETHERRACK
    - WARPED_NYLIUM:NETHERRACK
    - MYCELIUM:ROOTED_DIRT
    - MAGMA_BLOCK:LAVA

## Only relevant if Towny is installed
## Controls if paths can be made anywhere or only in locations where the player is allowed to break blocks
townyModifiers:
  pathsOnlyWherePlayerCanBreak: true
