## attemptFrequency controls how often DesirePaths will roll the dice to change blocks
## attemptFrequency is in ticks. 20 ticks = 1 second. IT IS HIGHLY DISCOURAGED TO SET THIS BELOW 5
## you can increase this number if you run into any performance issues but the effect of DesirePaths will be less pronounced
## THIS VALUE DOES NOT CHANGE WITH </desirepaths reload> YOU MUST RESTART THE SERVER FOR THIS TO TAKE EFFECT
attemptFrequency: 10

##chanceModifiers control the chance that a block below the player or at their feet will be changed
##Chances are out of 100
chanceModifiers:
  RIDING_HORSE: 37
  RIDING_BOAT: 99
  RIDING_PIG: 30
  FEATHER_FALLING: 10
  HAS_BOOTS: 20
  LEATHER_BOOTS: 11
  NO_BOOTS: 3
##These chances are slightly different, they are in addition to the chance from the other modifiers and are only added when the player is sprinting
  SPRINTING_BLOCK_BELOW: 13
  SPRINTING_BLOCK_AT_FEET: 100


## blockModifications are how DesirePaths knows which blocks to check for as well as what blocks they should turn into
## use blocks from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
## DO NOT add the same block twice
## avoid adding tons of blocks to this list as it could possibly affect performance
blockModifications:
## blockAtFeetModifications are the blocks at the same level as the players feet
  blockAtFeetModifications:
    - SNOW:AIR
    - GRASS:AIR
    - FERN:AIR
    - TALL_GRASS:GRASS
## blockBelowModifications are the blocks below that the player is standing on
  blockBelowModifications:
    - GRASS_BLOCK:DIRT
    - DIRT:COARSE_DIRT
    - PODZOL:COARSE_DIRT
    - COARSE_DIRT:DIRT_PATH
    - SANDSTONE:SAND
    - CRIMSON_NYLIUM:NETHERRACK
    - WARPED_NYLIUM:NETHERRACK
    - MYCELIUM:ROOTED_DIRT
    - MAGMA_BLOCK:LAVA

##If towny is installed this section will control if paths can be made anywhere or only where the player can break blocks
townyModifiers:
  pathsOnlyWherePlayerCanBreak: true

