name: DesirePaths
version: '${project.version}'
main: me.kermx.desirepaths.DesirePaths
api-version: 1.19
author: KermX
softdepend:
  - Towny
  - WorldGuard
commands:
  desirepaths:
    description: Base DesirePaths command
    usage: /desirepaths <arg>
