name: DesirePaths
version: '${project.version}'
main: me.kermx.desirepaths.DesirePaths
api-version: 1.19
author: KermX
softdepend:
  - Towny
  - WorldGuard
commands:
  desirepaths:
    description: Reload the configuration file for DesirePaths
    usage: /desirepaths <arg>
    permission: desirepaths.testperm
